name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure Google Cloud credentials
        run: echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp_credentials.json

      - name: Debug credentials file
        run: cat /tmp/gcp_credentials.json

      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="credentials=/tmp/gcp_credentials.json"

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_credentials: ${{ secrets.GCP_CREDENTIALS }}
